name: Release APK

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v1.1.5 등 태그 푸시 시 실행

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4' # pubspec.yaml에 명시된 버전과 맞춤 (또는 latest)
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          body: "New release ${GITHUB_REF_NAME}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
